from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    Boolean,
    DateTime,
    ForeignKey,
    JSON,
)
from sqlalchemy.orm import relationship
from app.database import Base


def get_utc_now():
    """Helper to return current UTC datetime."""
    return datetime.now(timezone.utc)


class ApprovalWorkflow(Base):
    """
    ApprovalWorkflow Model managing the multi-tier dynamic approval routing
    and lifecycle for an EventProposal.
    """
    __tablename__ = "approval_workflows"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    proposal_id = Column(String(36), ForeignKey("event_proposals.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    status = Column(String(50), default="Initiated", nullable=False, index=True)  # 'Initiated', 'In Progress', 'Approved', 'Rejected'
    current_step = Column(Integer, default=1, nullable=False)
    created_at = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)
    updated_at = Column(DateTime(timezone=True), default=get_utc_now, onupdate=get_utc_now, nullable=False)

    # Relationships
    proposal = relationship("EventProposal", backref="workflow", uselist=False)
    nodes = relationship("ApprovalNode", back_populates="workflow", cascade="all, delete-orphan", order_by="ApprovalNode.step_number", lazy="selectin")
    history = relationship("ApprovalHistory", back_populates="workflow", cascade="all, delete-orphan", order_by="ApprovalHistory.timestamp", lazy="selectin")
    risk_assessment = relationship("RiskAssessment", back_populates="workflow", uselist=False, cascade="all, delete-orphan", lazy="joined")

    def __repr__(self) -> str:
        return f"<ApprovalWorkflow(id={self.id}, proposal_id='{self.proposal_id}', status='{self.status}', step={self.current_step})>"


class ApprovalNode(Base):
    """
    ApprovalNode Model representing a discrete human review stage in the workflow.
    """
    __tablename__ = "approval_nodes"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(Integer, ForeignKey("approval_workflows.id", ondelete="CASCADE"), nullable=False, index=True)
    step_number = Column(Integer, nullable=False)
    required_role = Column(String(100), nullable=False)  # e.g., 'Faculty Advisor', 'Security Officer', 'Finance Officer', 'Admin'
    status = Column(String(50), default="Pending", nullable=False, index=True)  # 'Pending', 'Approved', 'Rejected'
    reviewer_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)

    # Relationships
    workflow = relationship("ApprovalWorkflow", back_populates="nodes")
    reviewer = relationship("User", backref="reviewed_nodes")

    def __repr__(self) -> str:
        return f"<ApprovalNode(id={self.id}, step={self.step_number}, role='{self.required_role}', status='{self.status}')>"


class ApprovalHistory(Base):
    """
    ApprovalHistory Model providing an immutable audit trail for all workflow events and decisions.
    """
    __tablename__ = "approval_histories"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(Integer, ForeignKey("approval_workflows.id", ondelete="CASCADE"), nullable=False, index=True)
    reviewer_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    action_taken = Column(String(50), nullable=False)  # 'Initiated', 'Approved', 'Rejected', 'Warning Flagged'
    remarks = Column(Text, nullable=True)
    timestamp = Column(DateTime(timezone=True), default=get_utc_now, nullable=False)

    # Relationships
    workflow = relationship("ApprovalWorkflow", back_populates="history")
    reviewer = relationship("User", backref="audit_actions")

    def __repr__(self) -> str:
        return f"<ApprovalHistory(id={self.id}, workflow_id={self.workflow_id}, action='{self.action_taken}', timestamp={self.timestamp})>"


class RiskAssessment(Base):
    """
    RiskAssessment Model generated by the ComplianceValidatorService storing
    pre-screening evaluation, high-risk flags, and mitigation suggestions.
    """
    __tablename__ = "risk_assessments"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    workflow_id = Column(Integer, ForeignKey("approval_workflows.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    risk_score = Column(Integer, default=0, nullable=False)  # Scale 0 - 100
    is_high_risk = Column(Boolean, default=False, nullable=False)
    flag_details = Column(JSON, nullable=True)  # List of warnings & suggestions

    # Relationship
    workflow = relationship("ApprovalWorkflow", back_populates="risk_assessment")

    def __repr__(self) -> str:
        return f"<RiskAssessment(id={self.id}, risk_score={self.risk_score}, is_high_risk={self.is_high_risk})>"

